repos:
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
      - id: black
        args: [--check, --diff]
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        # TODO: Commenting out max supported Python version until we pin it for Pymoca
        # language_version: python3.11
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          [flake8-bugbear, flake8-comprehensions, flake8-import-order]
        # This exclude list should be same as for black in pyproject.toml
        # See https://pre-commit.com/#regular-expressions for this syntax
        exclude: |
          (?x)^(
            src/pymoca/generated/.*|
            src/pymoca/_version.py|
            test/generated/.*|
            test/libraries/.*
          )$
